// Player_Character.h

#pragma once

// =========================
// Includes
// =========================

#include "CoreMinimal.h"
#include "GameFramework/Character.h"
#include "Units.h"
#include "GridManager.h"
#include "Player_Character.generated.h"

// =========================
// Animation states used
// by the character
// =========================

UENUM(BlueprintType)
enum class EAnimationState : uint8
{
	IDLE,
	WALK,
	ATTACK
};

// =========================
// Player class controlled
// by the turn system
// =========================

UCLASS()
class TRPG_GAME_API APlayer_Character : public AUnits
{
	GENERATED_BODY()

public:

	APlayer_Character();

protected:

	// =========================
	// Initialization
	// =========================

	virtual void BeginPlay() override;

public:

	// =========================
	// Tick
	// =========================

	virtual void Tick(float DeltaTime) override;

	// =========================
	// Interaction
	// =========================

	// Called when the unit is clicked
	UFUNCTION()
	void OnPlayerClicked(
		UPrimitiveComponent* TouchedComponent,
		FKey ButtonPressed
	);

	// =========================
	// Interface
	// =========================

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TSubclassOf<UUserWidget> StatsWidgetClass;

	UPROPERTY()
	UUserWidget* StatsWidget;

	// =========================
	// Selection
	// =========================

	UPROPERTY(BlueprintReadOnly)
	bool bIsSelected = false;

	// =========================
	// Movement
	// =========================

	// Moves the unit along the calculated path
	void MoveAlongPath(float DeltaTime);

	// =========================
	// Functions
	// =========================

	void SelectPlayer();

	void UnselectPlayer();

	// Stores the actual tile type
	// before it becomes occupied
	UPROPERTY()
	ETileType PreviousTileType;

	UFUNCTION()
	void ResetToIdle();

	// =========================
	// Movement variables
	// =========================

	FTimerHandle AttackTimer;

	int CurrentTileIndex = -1;

	float BaseMoveSpeed;

	// Movement generated by a skill
	bool bSkillMovement = false;

	// Prevents certain actions during an animation
	bool bLockActions = false;
};